#!/bin/bash

#Aborting the commit if the files contain any passwords.
files=$(git diff --cached --name-only --diff-filter=AM -- `find . -name '*.yml'`)

if [ -n "$files" ]; then
    if grep -E "password[ ]*[:|=][ ]*[a-z|A-Z|0-9]+" $files; then
        echo "$(tput setaf 1)Blocking the commit as a password was found.Please remove all the passwords and retry the commit."
        exit 1
    fi
fi


#Abort the commit if the unit test cases fail
./gradlew test

RESULT=$?
if [ $RESULT -gt 0 ] ; then
  echo "$(tput setaf 1)You have failing unit test(s). Please fix them and re-try committing."
fi

exit $RESULT
